server:
  port: 8080

spring:
  datasource:
    name: blog
    # type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.96.176.80:3306/blog
    username: blog
    password: Blog@1234
    driver-class-name: com.mysql.jdbc.Driver
    #   filters: stat
    #   maxActive: 20
    #   initialSize: 1
    #   maxWait: 60000
    #  minIdle: 1
    #  timeBetweenEvictionRunsMillis: 60000
    #  minEvictableIdleTimeMillis: 300000
    #  validationQuery: select 'x'
    #  testWhileIdle: true
    #  testOnBorrow: false
    #  testOnReturn: false
    #  poolPreparedStatements: true
  #  maxOpenPreparedStatements: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

## 该配置节点为独立的节点，如果将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xsx.blog.model  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql